#!/bin/bash

echo "🔧 CONFIGURACIÓN DE VERCEL KV"
echo "============================="
echo ""

echo "📋 PASOS PARA OBTENER LAS VARIABLES KV:"
echo ""
echo "1. 🌐 Ve a: https://vercel.com/dashboard"
echo "2. 📁 Selecciona tu proyecto: 'prueba'"
echo "3. 💾 Ve a la pestaña 'Storage'"
echo "4. ➕ Click en 'Create Database'"
echo "5. 🔴 Selecciona 'KV (Redis)'"
echo "6. 📝 Nombre: 'short-urls-storage'"
echo "7. 🌍 Región: US East (recomendado)"
echo "8. ✅ Click 'Create'"
echo ""
echo "9. 📋 Una vez creado, ve a la pestaña 'Settings' de la base de datos"
echo "10. 🔑 Copia las variables de entorno:"
echo "    - KV_REST_API_URL"
echo "    - KV_REST_API_TOKEN"
echo ""
echo "11. ⚙️ Agregar variables al proyecto:"
echo "    vercel env add KV_REST_API_URL"
echo "    vercel env add KV_REST_API_TOKEN"
echo ""
echo "12. 🚀 Hacer nuevo deployment:"
echo "    vercel --prod"
echo ""
echo "📖 Documentación: https://vercel.com/docs/storage/vercel-kv/quickstart"
echo ""
echo "🔍 Para verificar que funciona:"
echo "   curl https://prueba-1es5iooo3-rsamanezs-projects.vercel.app/api/health"